package ebanking.dao;

import ebanking.exceptions.UserNotFoundException;
import ebanking.model.User;
import org.slf4j.Logger;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import static org.slf4j.LoggerFactory.getLogger;

/**
 * @author <a href="mailto:a.groumas@app-art.gr">Aggelos Groumas</a>
 */
public class UserDAO {
    private static final Logger LOGGER = getLogger(UserDAO.class);
    private Connection connection;

    public UserDAO(Connection connection) {
        this.connection = connection;
    }

    public User findUserByUsername(String username) throws UserNotFoundException {
        User found = null;
        String findUserByUsernameQuery = "SELECT * FROM user WHERE username = ?";
        PreparedStatement pst;
        ResultSet rs;

        try {
            pst = connection.prepareStatement(findUserByUsernameQuery);
            pst.setString(1, username);
            rs = pst.executeQuery();
            if (rs.next()) {
                found = new User(rs.getInt("id"), rs.getString("firstname"), rs.getString("lastname"),
                        rs.getString("username"), rs.getString("password"), rs.getString("password"));
            } else {
                throw new UserNotFoundException(String.format("User with username: %s not found\n", username));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return found;
    }

    public int save(User user) {
        String insertQuery = "INSERT INTO User(firstname, lastname, username, password, email) VALUES (?, ?, ?, ?, ?)";
        int autoGeneratedID = -1;
        try {
            PreparedStatement pst = connection.prepareStatement(insertQuery);
            pst.setString(1, user.getFirstName());
            pst.setString(2, user.getLastName());
            pst.setString(3, user.getUsername());
            pst.setString(4, user.getPassword());
            pst.setString(5, user.getEmail());
            pst.executeUpdate();

            ResultSet tableKeys = pst.getGeneratedKeys();
            tableKeys.next();
            autoGeneratedID = tableKeys.getInt(1);
            LOGGER.debug("User {} saved. ID is {}\n", user.getFirstName(), autoGeneratedID);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return autoGeneratedID;
    }
}
